services:
  php:
    build:
      context: ./php
      dockerfile: DockerFile
    container_name: php82_revato
    volumes:
      - ./api:/var/www
    depends_on:
      - database

  caddy:
    image: caddy:2
    container_name: caddy
    ports:
      - 8000:80
    volumes:
      - ./api/public:/srv
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - php
  database:
    image: mariadb:11.4
    container_name: database_revato
    command: --default-authentication-plugin=mysql_native_password
    environment:
       MYSQL_ROOT_PASSWORD: pass
       MYSQL_DATABASE: revatodb
       MYSQL_USER: test
       MYSQL_PASSWORD: pass
    ports:
      - 3307:3306
    volumes:
      - revato_db:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_revato
    environment:
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: pass
      UPLOAD_LIMIT: 20M
    ports:
      - "8899:80"
  mailhog:
    image: mailhog/mailhog
    logging:
      driver: "none"
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  revato_db: