name: Deploy Symfony API to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name:  Deploy to VPS
    runs-on: ubuntu-latest

    steps:
      - name:  Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo, pdo_mysql, intl, dom, curl, openssl

      - name:  Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      - name:  Upload files to VPS
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "api"
          target: "/var/www/symfony-api"

      - name:  Run deployment commands on VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /var/www/symfony-api
            php bin/console cache:clear
            php bin/console doctrine:migrations:migrate --no-interaction
            systemctl reload php8.2-fpm
